### ISSUE TITLE
inference: GPU backend uses explicit attention score buffer, not flash attention

### ISSUE THREAD

**Issue by ohdearquant** [ohdearquant/lattice#13]
## Problem

`GpuBackend` materializes an explicit `[num_heads, seq, seq]` attention score buffer rather than using the tiled flash-attention approach available on CPU. This caps practical GPU context length compared to the CPU tiled paths.

## Impact

GPU inference on long sequences will OOM earlier than CPU inference for the same model, which is counterintuitive. The CPU path uses flash tiling (48KB L1 budget, Br=Bc=64) but the GPU path doesn't.

## Suggested Fix

Port the flash-attention tiling strategy to the Metal/GPU compute kernels, or document the context length ceiling for GPU inference.

Surfaced during KG codebase ingestion.

**Comment by ohdearquant** [comment]
Closing — the premise no longer holds against the current codebase (verified 2026-06-23):

1. **The `GpuBackend` struct is gone.** A grep for `struct GpuBackend` returns nothing; the Metal attention path was restructured.
2. **No full `[num_heads, seq, seq]` score buffer is materialized.** The current prefill attention kernel `prefill_attention_batched_causal` (`crates/inference/src/forward/metal_qwen35.rs:2498`) uses **tiled online-softmax**: a `score_s[MAX_GRP * TILE_TOKENS]` tile (TILE_TOKENS=256, ~17KB threadgroup memory) streamed over the KV cache with running-max rescaling — the same memory-bounded "flash" approach this issue asked for. There is no `O(seq²)` device allocation, so the GPU-OOM-earlier-than-CPU ceiling described here does not exist.

The remaining, orthogonal concern — the prefill kernel tiles the **KV** dimension only (one threadgroup per query token) rather than tiling the **Q** dimension FA2-style for peak bandwidth at very long contexts — is tracked by **#126**. The correctness/OOM concern in this issue is resolved.
